name: .NET

on: [ push, pull_request ]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build rm.Random2.sln \
          -c Release
    # net5.0 only as test csproj also targets others
    - name: Test
      run: |
        dotnet test tests/rm.Random2Test/rm.Random2Test.csproj \
          -c Release --no-build --no-restore \
          -f net5.0 \
          -v normal \
          --filter "TestCategory!=very.slow"
